
spring:
  application:
    name: service-client
    version: v1

server:
  port: 8080
  servlet:
    context-path: /v1

eureka:
  instance:
    instanceId: ${spring.application.name}-${spring.application.version}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_PROTOCOL:http}://${EUREKA_SERVER_HOST:localhost}:${EUREKA_SERVER_PORT:8761}/eureka/
