
server:  port: 8761
  
eureka:  instance:    hostname: ${SERVER_HOSTNAME:localhost}
  client:    register-with-eureka: false
    fetch-registry: false
    service-url:      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/